apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      initContainers:
        - name: db-init
          image: ghcr.io/aokiapp/plasmic-k8s/backend:latest
          command:
            [
              "bash",
              "tools/run.bash",
              "/app/src/wab/server/db/create-system-acct.ts",
            ]
          envFrom:
            - secretRef:
                name: shared-secret
            - configMapRef:
                name: shared-cm
          env:
            - name: NFIGURE_JSON
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: config.json
            - name: NFIGURE_PATCH_JSON
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: secret.json
      containers:
        - name: backend
          image: ghcr.io/aokiapp/plasmic-k8s/backend:latest
          ports:
            - containerPort: 3004
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3004
            initialDelaySeconds: 3
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: shared-secret
            - configMapRef:
                name: shared-cm
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_REGION
            - name: NFIGURE_JSON
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: config.json
            - name: NFIGURE_PATCH_JSON
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: secret.json
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
  type: ClusterIP

---

