apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
  labels:
    app: frontend
  annotations:
    description: "Frontend build parameter, used in wab/client"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: github-registry-secret

      containers:
        - name: frontend
          image: ghcr.io/aokiapp/plasmic-k8s/frontend:latest
          envFrom:
            - configMapRef:
                name: frontend-cm
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
