resources:
  - namespace.yaml
  - database.yaml
  - backend.yaml
  - ingress.yaml
  - shared.yaml
  - frontend.yaml
  - codegen.yaml

configMapGenerator:
  - name: backend-config
    files:
      - config.json
