resources:
  - namespace.yaml
  - database.yaml
  - backend.yaml
  - ingress.yaml
  - shared.yaml
  - frontend.yaml

configMapGenerator:
  - name: backend-config
    files:
      - config.json

secretGenerator:
  - name: backend-secret
    files:
      - secret.json
    type: Opaque
