apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-cm
  annotations:
    description: "Environment variables used in wab/shared"

data:
  NODE_ENV: "development"
  REACT_APP_DEFAULT_HOST_URL: "https://host.plasmicdev.com/static/host.html"
  REACT_APP_PUBLIC_URL: "http://localhost:3003"
  CODEGEN_HOST: "https://codegen.plasmic.app"
  CODEGEN_ORIGIN_HOST: "http://codegen-origin.plasmic.app"
  INTEGRATIONS_HOST: "https://integrations.plasmic.app"

---
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  annotations:
    description: "All secret environment variables are here"
type: Opaque
