namespace: plasmic
resources:
  - ../base
patches:
  - path: ingress.yaml
  - path: shared-cm.yaml
  - path: shared-secret.yaml

configMapGenerator:
  - name: backend-config
    files:
      - config.json

secretGenerator:
  - name: backend-secret
    files:
      - secret.json
    type: Opaque
