namespace: plasmic
resources:
  - ../base
patches:
  - path: ingress.yaml
  - path: shared-cm.yaml
  - path: shared-secret.yaml

configMapGenerator:
  - name: backend-config
    behavior: replace
    files:
      - config.json
